# Generated by Django 3.2.8 on 2021-10-20 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date and time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_articlecomments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.article', verbose_name='Article comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date and time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_newss', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_newscomments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.news', verbose_name='News comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteNewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(blank=True, choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=50, verbose_name='Vote type')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_votenewscomments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('vote_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.newscomment', verbose_name='Vote news comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(blank=True, choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=50, verbose_name='Vote type')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_votenewss', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.news', verbose_name='Vote news')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(blank=True, choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=50, verbose_name='Vote type')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_votearticlecomments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('vote_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.articlecomment', verbose_name='Vote article comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(blank=True, choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=50, verbose_name='Vote type')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_votearticles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.article', verbose_name='Vote article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
