# Generated by Django 3.2.8 on 2021-10-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211020_1412'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='votearticle',
            name='api_votearticle_check_unique',
        ),
        migrations.RemoveConstraint(
            model_name='votearticlecomment',
            name='api_votearticlecomment_check_unique',
        ),
        migrations.RemoveConstraint(
            model_name='votenews',
            name='api_votenews_check_unique',
        ),
        migrations.RemoveConstraint(
            model_name='votenewscomment',
            name='api_votenewscomment_check_unique',
        ),
        migrations.RenameField(
            model_name='votearticle',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='votearticlecomment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='votenews',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='votenewscomment',
            old_name='author',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='votearticle',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='api_votearticle_check_unique'),
        ),
        migrations.AddConstraint(
            model_name='votearticlecomment',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='api_votearticlecomment_check_unique'),
        ),
        migrations.AddConstraint(
            model_name='votenews',
            constraint=models.UniqueConstraint(fields=('news', 'user'), name='api_votenews_check_unique'),
        ),
        migrations.AddConstraint(
            model_name='votenewscomment',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='api_votenewscomment_check_unique'),
        ),
    ]
